ibrary(
  identifier: 'jenkins-pipeline-library@master',
  retriever: modernSCM(
    [
      $class: 'GitSCMSource',
      remote: 'https://github.com/viafoura/jenkins-pipeline-library.git',
      credentialsId: 'github-app'
    ]
  )
)


vfStandardGradlePipeline(
  debug: true,
  mode: 'kube',
  defaultBuildImage: '218894879100.dkr.ecr.us-east-1.amazonaws.com/corretto-11-jdk-alpine:latest',
  defaultShell: '/bin/sh',
  repo: '218894879100.dkr.ecr.us-east-1.amazonaws.com',
  dockerTarget: '{{ cookiecutter.project_slug }}',
  slackChannel: "jenkins-notifications",
  slackIcon_status_unstable: ":despair:",
  preMergeActions: {}
)